In [14]:
#2) Import the required classification libraries along with pandas, numpy, seaborn etc
#3) Then import the classifiers from them (Randomforest, SVM, NaiveBayes, DecisionTrees)
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

In [15]:
os.chdir("D:\\DS\\Python DS\\Project\\574_cert_proj_dataset_v3.0\\")

In [16]:
#1) Import the train and test csv.
#Read the data file
dataset_train=pd.read_csv("train.csv")
dataset_test=pd.read_csv("test.csv")

In [17]:
dataset_train.head(4)

id                species   margin1   margin2   margin3   margin4  \
0   1            Acer_Opalus  0.007812  0.023438  0.023438  0.003906   
1   2  Pterocarya_Stenoptera  0.005859  0.000000  0.031250  0.015625   
2   3   Quercus_Hartwissiana  0.005859  0.009766  0.019531  0.007812   
3   5        Tilia_Tomentosa  0.000000  0.003906  0.023438  0.005859   

    margin5   margin6   margin7  margin8  ...  texture55  texture56  \
0  0.011719  0.009766  0.027344      0.0  ...   0.007812   0.000000   
1  0.025391  0.001953  0.019531      0.0  ...   0.000977   0.000000   
2  0.003906  0.005859  0.068359      0.0  ...   0.154300   0.000000   
3  0.021484  0.019531  0.023438      0.0  ...   0.000000   0.000977   

   texture57  texture58  texture59  texture60  texture61  texture62  \
0   0.002930   0.002930   0.035156        0.0        0.0   0.004883   
1   0.000000   0.000977   0.023438        0.0        0.0   0.000977   
2   0.005859   0.000977   0.007812        0.0        0.0   0.000000   
3   0.000000   0.000000   0.020508        0.0        0.0   0.017578   

   texture63  texture64  
0   0.000000   0.025391  
1   0.039062   0.022461  
2   0.020508   0.002930  
3   0.000000   0.047852  

[4 rows x 194 columns]

In [18]:
dataset_test

id   margin1   margin2   margin3   margin4   margin5   margin6  \
0       4  0.019531  0.009766  0.078125  0.011719  0.003906  0.015625   
1       7  0.007812  0.005859  0.064453  0.009766  0.003906  0.013672   
2       9  0.000000  0.000000  0.001953  0.021484  0.041016  0.000000   
3      12  0.000000  0.000000  0.009766  0.011719  0.017578  0.000000   
4      13  0.001953  0.000000  0.015625  0.009766  0.039062  0.000000   
5      16  0.021484  0.033203  0.021484  0.009766  0.015625  0.035156   
6      19  0.015625  0.025391  0.046875  0.009766  0.005859  0.027344   
7      23  0.007812  0.031250  0.011719  0.050781  0.000000  0.117190   
8      24  0.003906  0.007812  0.074219  0.017578  0.015625  0.003906   
9      28  0.000000  0.000000  0.005859  0.021484  0.054688  0.000000   
10     33  0.025391  0.041016  0.033203  0.017578  0.009766  0.056641   
11     36  0.001953  0.009766  0.025391  0.003906  0.015625  0.003906   
12     39  0.013672  0.000000  0.046875  0.019531  0.005859  0.000000   
13     41  0.007812  0.005859  0.060547  0.013672  0.011719  0.000000   
14     44  0.017578  0.039062  0.031250  0.005859  0.005859  0.039062   
15     46  0.011719  0.017578  0.111330  0.009766  0.007812  0.011719   
16     47  0.025391  0.015625  0.132810  0.003906  0.001953  0.009766   
17     51  0.007812  0.007812  0.019531  0.039062  0.031250  0.021484   
18     52  0.001953  0.007812  0.031250  0.005859  0.013672  0.003906   
19     53  0.000000  0.000000  0.082031  0.111330  0.017578  0.000000   
20     57  0.013672  0.023438  0.007812  0.054688  0.001953  0.083984   
21     59  0.011719  0.011719  0.048828  0.005859  0.007812  0.015625   
22     62  0.037109  0.158200  0.013672  0.009766  0.000000  0.203130   
23     65  0.027344  0.056641  0.021484  0.011719  0.005859  0.019531   
24     68  0.000000  0.000000  0.003906  0.021484  0.023438  0.000000   
25     70  0.015625  0.023438  0.025391  0.011719  0.005859  0.005859   
26     74  0.019531  0.064453  0.009766  0.039062  0.000000  0.138670   
27     77  0.000000  0.095703  0.000000  0.017578  0.000000  0.000000   
28     79  0.001953  0.000000  0.015625  0.113280  0.023438  0.000000   
29     86  0.017578  0.078125  0.023438  0.003906  0.001953  0.048828   
..    ...       ...       ...       ...       ...       ...       ...   
564  1493  0.005859  0.000000  0.021484  0.039062  0.011719  0.003906   
565  1495  0.007812  0.015625  0.058594  0.023438  0.027344  0.013672   
566  1497  0.005859  0.005859  0.009766  0.005859  0.074219  0.001953   
567  1498  0.021484  0.015625  0.078125  0.019531  0.003906  0.044922   
568  1503  0.041016  0.142580  0.021484  0.001953  0.000000  0.154300   
569  1510  0.001953  0.000000  0.009766  0.015625  0.027344  0.000000   
570  1513  0.011719  0.007812  0.021484  0.001953  0.041016  0.001953   
571  1517  0.000000  0.000000  0.097656  0.052734  0.005859  0.000000   
572  1522  0.001953  0.005859  0.025391  0.011719  0.007812  0.000000   
573  1526  0.015625  0.017578  0.074219  0.011719  0.001953  0.015625   
574  1528  0.074219  0.064453  0.013672  0.003906  0.000000  0.244140   
575  1533  0.017578  0.017578  0.031250  0.009766  0.003906  0.015625   
576  1534  0.001953  0.000000  0.017578  0.011719  0.027344  0.003906   
577  1535  0.042969  0.144530  0.035156  0.005859  0.000000  0.130860   
578  1537  0.003906  0.003906  0.021484  0.011719  0.046875  0.003906   
579  1540  0.000000  0.001953  0.015625  0.013672  0.029297  0.001953   
580  1542  0.005859  0.011719  0.033203  0.001953  0.035156  0.015625   
581  1546  0.011719  0.013672  0.017578  0.007812  0.007812  0.005859   
582  1553  0.009766  0.001953  0.044922  0.015625  0.021484  0.003906   
583  1558  0.001953  0.000000  0.009766  0.001953  0.021484  0.005859   
584  1560  0.042969  0.107420  0.025391  0.011719  0.003906  0.115230   
585  1564  0.009766  0.025391  0.064453  0.005859  0.001953  0.095703   
586  1565  0.007812  0.019531  0.013672  0.031250  0.011719  0.00

In [19]:
len(dataset_train.columns)

194

In [20]:
len(dataset_test.columns)

193

In [21]:
#4) After this create a function to encode the labels of the strings given in the dataset
x=dataset_train.iloc[:,2:].values

In [22]:
y=dataset_train.iloc[:,1].values

In [23]:
x_dataset_test=dataset_test.iloc[:,1:].values

In [24]:
x_dataset_test

array([[0.019531, 0.009766, 0.078125, ..., 0.      , 0.003906, 0.053711],
       [0.007812, 0.005859, 0.064453, ..., 0.000977, 0.037109, 0.044922],
       [0.      , 0.      , 0.001953, ..., 0.015625, 0.      , 0.      ],
       ...,
       [0.017578, 0.029297, 0.015625, ..., 0.      , 0.042969, 0.006836],
       [0.013672, 0.009766, 0.060547, ..., 0.      , 0.011719, 0.018555],
       [0.      , 0.11719 , 0.      , ..., 0.015625, 0.      , 0.017578]])

In [11]:
y

array(['Acer_Opalus', 'Pterocarya_Stenoptera', 'Quercus_Hartwissiana',
       'Tilia_Tomentosa', 'Quercus_Variabilis', 'Magnolia_Salicifolia',
       'Quercus_Canariensis', 'Quercus_Rubra', 'Quercus_Brantii',
       'Salix_Fragilis', 'Zelkova_Serrata', 'Betula_Austrosinensis',
       'Quercus_Pontica', 'Quercus_Afares', 'Quercus_Coccifera',
       'Fagus_Sylvatica', 'Phildelphus', 'Acer_Palmatum',
       'Quercus_Pubescens', 'Populus_Adenopoda', 'Quercus_Trojana',
       'Quercus_Variabilis', 'Alnus_Sieboldiana', 'Quercus_Ilex',
       'Arundinaria_Simonii', 'Acer_Platanoids', 'Quercus_Phillyraeoides',
       'Cornus_Chinensis', 'Quercus_Phillyraeoides', 'Fagus_Sylvatica',
       'Liriodendron_Tulipifera', 'Cytisus_Battandieri',
       'Tilia_Tomentosa', 'Rhododendron_x_Russellianum', 'Alnus_Rubra',
       'Eucalyptus_Glaucescens', 'Cercis_Siliquastrum',
       'Cotinus_Coggygria', 'Celtis_Koraiensis', 'Quercus_Crassifolia',
       'Quercus_Variabilis', 'Quercus_Hartwissiana', 'Quercus

In [25]:
#5) You can do the above step using label encoder. With this you are creating some labels
#from train set as test set. The test set we imported is for testing the best classifier
#accuracy once we choose it
from sklearn.preprocessing import LabelEncoder
labelx=LabelEncoder()
y=labelx.fit_transform(y)

In [26]:
y

array([ 3, 49, 65, 94, 84, 40, 54, 78, 53, 89, 98, 16, 74, 50, 58, 31, 43,
        4, 75, 44, 83, 84, 13, 66, 15,  6, 73, 22, 73, 31, 36, 27, 94, 88,
       12, 28, 21, 25, 20, 60, 84, 65, 69, 58, 23, 76, 18, 52, 54,  9, 48,
       47, 64, 81, 83, 36, 58, 21, 81, 20, 62, 88, 34, 92, 79, 82, 20, 32,
        4, 84, 36, 35, 72, 60, 71, 72, 52, 50, 54, 11, 51, 18, 47,  5,  8,
       37, 97, 20, 33,  1, 59,  1, 56,  1,  9, 57, 20, 79, 29, 16, 32, 54,
       93, 10, 46, 59, 84, 76, 15, 10, 15,  0, 69,  4, 51, 51, 94, 36, 39,
       62,  2, 24, 26, 35, 25, 87,  0, 55, 34, 38,  1, 45,  7, 93, 56, 38,
       21, 51, 75, 81, 74, 33, 20, 37,  9, 40, 60, 31, 83, 50, 71, 67, 30,
       66,  1, 43, 61, 23, 65, 84, 87, 46, 57, 16,  2, 28, 12, 96, 44, 76,
       29, 75, 41, 87, 67, 61, 30,  5, 12, 62,  3, 83, 81,  6, 85,  4, 37,
       57, 84, 39, 71, 61,  6, 76, 14, 31, 98, 40, 17, 51, 16, 42, 63, 86,
       37, 69, 86, 71, 80, 78, 14, 35, 25,  5, 39,  8,  9, 26, 44, 60, 13,
       14, 77, 13, 80, 87

In [27]:
#6) Then extract the values from train set by stratifying them and dividing it into 80:20 ratio
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [28]:
#Model - KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier
class_k=KNeighborsClassifier(n_neighbors=5, metric="minkowski", p=2)
class_k.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [30]:
#Predict
y_pred_k = class_k.predict(x_test)

In [31]:
#Predict _Test
y_pred_k_test = class_k.predict(x_dataset_test)

In [33]:
y_pred_k

array([20, 51, 79,  2, 17, 35, 33, 58,  3, 14, 41, 33, 61, 90, 52, 26, 43,
       19, 75, 86, 95,  4, 88, 89, 85, 34, 29, 39, 36, 33, 90,  8,  9, 62,
       68,  4, 64, 38, 56, 37, 21, 65, 54, 30, 60, 51, 59, 17, 46, 57, 78,
       32, 64, 37, 56, 23,  6,  6, 76, 78, 59, 30, 46, 68, 87, 11, 80, 50,
       56, 61, 69, 46, 23, 71, 68, 69, 97, 96, 61, 12, 57, 77, 74, 16, 29,
        3, 60, 49, 66, 62, 91, 94, 58, 23, 64, 47, 45, 83, 72, 46, 27, 24,
       31, 32, 67, 37, 39, 90, 10, 50, 65, 30, 19, 77, 37, 75,  0, 49, 48,
       68, 68, 13, 53, 58, 73, 46, 77, 28, 84, 76,  3, 26, 80, 21, 11, 12,
       79, 24, 37,  8, 31, 89, 83, 22, 44,  0, 76, 59, 41, 82, 80, 74, 75,
       58, 51, 45, 85, 11, 92, 18, 19, 20, 80, 56, 93,  2, 53, 75, 70, 68,
       19, 28, 28, 62, 90, 36, 16, 52,  8, 93, 34, 54, 23, 16, 18, 78, 24,
       49, 51, 71,  4, 95, 90, 82, 60, 69,  3, 39])

In [34]:
y_pred_k_test

array([51, 50,  1, 19, 14, 83,  3, 28, 84,  8, 43, 74, 75, 10, 52, 46, 31,
       68, 13, 71, 61, 54, 57, 77,  1, 70, 28, 15, 35, 70, 53, 74, 47, 50,
        4, 36, 14, 55, 21, 93,  8, 32,  8,  9, 71, 70, 38, 23, 10, 18, 13,
        5, 55, 94, 14, 86, 62, 33, 51, 54, 88, 56, 21, 59, 65, 11, 48,  5,
       13,  4, 54, 44, 29,  7, 68, 98, 92, 84, 25, 10, 61, 27, 85, 24,  1,
        2, 23, 83, 40, 22, 41, 90, 25, 21, 37, 56, 41, 95,  7, 48, 98, 77,
        3, 12, 68, 84, 53, 96, 64, 72, 93, 93, 67, 30,  8, 88, 60, 87,  6,
       17, 40, 31, 60, 17, 86, 27, 51,  7, 39, 23, 96,  2, 41, 61, 24, 97,
       28, 29, 68, 81, 42, 51, 56, 62, 60, 52, 95,  3, 42, 96, 95, 20, 59,
       35, 86,  1, 56, 38, 43, 75, 20, 60, 46, 79, 22, 79, 69, 87, 65, 97,
       75, 21, 29, 21, 11, 10, 27, 94, 27, 22, 15, 45, 89, 54, 43,  5, 23,
       94, 40, 49, 89, 72, 36, 11, 64, 95, 18, 91, 29, 64, 80,  6, 78, 45,
       28,  9, 78, 90, 44, 89, 92, 13, 31, 59,  0, 96, 70, 32, 29, 78, 91,
       51, 44, 38,  5, 60

In [35]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred_k)

array([[2, 0, 0, ..., 0, 0, 0],
       [0, 2, 0, ..., 0, 0, 0],
       [0, 0, 2, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [39]:
#Naive Bayes
from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()
classifier_nb.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [40]:
y_pred_nb = classifier_nb.predict(x_test)
#Accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred_k)

0.7929292929292929

In [41]:
y_pred_nb

array([74, 51, 79,  2, 17, 35, 33, 58, 81, 14, 41, 84, 61, 90, 52, 26, 85,
       47, 51, 50, 47, 19, 88, 86, 85, 34, 38, 39, 36, 19, 68, 19, 85, 97,
       19,  4, 64, 38, 51, 87, 50, 85, 54, 30, 92, 85, 59, 17, 56, 44, 19,
       64, 64, 38, 85, 96,  6,  6, 85, 19, 59, 81, 51, 68, 47, 41, 19, 50,
       51, 61, 93, 51, 65, 80, 50, 58, 97, 53, 61, 12, 44, 77, 74, 11, 29,
        3, 79, 49, 66, 62, 86, 94, 58, 70, 51, 47, 45, 50, 70, 93, 27, 85,
       45, 32, 47, 34, 70, 69, 10,  3, 65, 30, 47, 77, 87, 55,  0, 49, 85,
       58, 85, 41, 53, 58, 26, 54, 19, 34, 84, 76, 69, 41, 19, 46, 14, 12,
       79, 24, 87,  8, 54, 89, 50, 22, 17, 20, 87, 59, 41, 59, 80, 74, 75,
       58, 79, 45, 19, 11, 14, 43, 19, 20, 26, 26, 12,  2, 12, 83, 19, 41,
       98, 29, 67, 62, 69, 79, 16, 50,  8, 93, 28, 85, 65, 16, 69, 19, 43,
       49, 51, 63,  1, 41, 69, 82, 79, 96,  3, 87])

In [42]:
#SVM - Linear
from sklearn.svm import SVC
class_linear=SVC(kernel='linear')
class_linear.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [43]:
y_pred_linear=class_linear.predict(x_test)

In [44]:
#Accuracy
accuracy_score(y_test, y_pred_linear)

0.03535353535353535

In [45]:
#SVM - RBF
from sklearn.svm import SVC
class_rbf=SVC(kernel='rbf')
class_rbf.fit(x_train,y_train)

D:\DS\anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [46]:
y_pred_rbf=class_rbf.predict(x_test)

In [47]:
#Accuracy
accuracy_score(y_test, y_pred_rbf)

0.0

In [48]:
#SVM - Sigmoid
from sklearn.svm import SVC
class_sigmoid=SVC(kernel='sigmoid')
class_sigmoid.fit(x_train,y_train)

D:\DS\anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [49]:
y_pred_sigmoid=class_sigmoid.predict(x_test)

In [50]:
#Accuracy
accuracy_score(y_test, y_pred_sigmoid)

0.0

In [51]:
# # #Entropy - Decision Tree
from sklearn.tree import DecisionTreeClassifier
class_tree=DecisionTreeClassifier(criterion="entropy")
class_tree.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [52]:
y_pred_tree=class_tree.predict(x_test)

In [53]:
accuracy_score(y_test, y_pred_tree)

0.6111111111111112

In [54]:
from sklearn.ensemble import RandomForestClassifier
class_random = RandomForestClassifier(n_estimators=3, criterion="entropy")
class_random.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=3, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [55]:
y_pred_random=class_random.predict(x_test)

In [56]:
accuracy_score(y_test, y_pred_random)

0.5555555555555556

In [57]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cmknn=confusion_matrix(y_test, y_pred_k)
cmnb=confusion_matrix(y_test, y_pred_nb)
cmlinear=confusion_matrix(y_test, y_pred_linear)
cmrbf=confusion_matrix(y_test, y_pred_rbf)
cmsigmoid=confusion_matrix(y_test, y_pred_sigmoid)
cmtree=confusion_matrix(y_test, y_pred_tree)
cmrandom=confusion_matrix(y_test, y_pred_random)

In [58]:
(cmknn[0,0]+cmknn[1,1])/sum(sum(cmknn))

0.020202020202020204

In [59]:
(cmnb[0,0]+cmnb[1,1])/sum(sum(cmnb))


0.005050505050505051

In [60]:
(cmlinear[0,0]+cmlinear[1,1])/sum(sum(cmlinear))

0.0

In [61]:
(cmrbf[0,0]+cmrbf[1,1])/sum(sum(cmrbf))

0.0

In [62]:
(cmsigmoid[0,0]+cmsigmoid[1,1])/sum(sum(cmsigmoid))

0.0

In [63]:
(cmtree[0,0]+cmtree[1,1])/sum(sum(cmtree))

0.015151515151515152

In [64]:
(cmrandom[0,0]+cmrandom[1,1])/sum(sum(cmrandom))

0.005050505050505051